#!/usr/bin/env bash
# Onboard one project/environment onto this monitoring stack.
#
#   ./bootstrap.sh <project> <env>
#
# It does the four things a human would otherwise get subtly wrong:
#
#   1. renders the keystone ProjectTelemetrySilent rule and reloads Grafana;
#   2. regenerates the coverage rule, so a project that ships telemetry without ever
#      being bootstrapped is itself alerted on;
#   3. creates the project's healthchecks.io checks (if an API key is present) and
#      prints their ping URLs;
#   4. prints the `.env` block to paste on the project host, and the curl that vendors
#      the templates at a pinned tag.
#
# Bootstrap is what creates the safety net, NOT the telemetry. A host can ship perfectly
# good telemetry and still be unmonitored, because the rule that notices its silence
# lives here. That asymmetry is the whole reason this script exists.
#
# Idempotent: re-running it re-renders the same files and reloads again.
set -euo pipefail

project="${1:-}"
env_name="${2:-}"
if [[ -z "$project" || -z "$env_name" ]]; then
    echo "usage: $0 <project> <env>" >&2
    exit 2
fi
# These become Prometheus label values, a Grafana rule uid, and a filename. Keep them
# boring: a label value with a quote or a brace in it produces a rule that silently
# never matches, which is the failure mode this whole stack exists to avoid.
if [[ ! "$project" =~ ^[a-z0-9][a-z0-9-]*$ || ! "$env_name" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    echo "error: project and env must match [a-z0-9][a-z0-9-]* (lowercase, no spaces)" >&2
    exit 2
fi

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$root"

# Read HEALTHCHECKS_API_KEY from .env if the environment does not already carry it.
# `just` recipes get .env via dotenv-load; a bare ./bootstrap.sh does not, and silently
# skipping check creation because of that is a confusing way to find out. Only this one
# key is read — sourcing the whole file would drag the stack's secrets into scope.
#
# It must be the project's READ-WRITE API key: the read-only key cannot POST, and a ping
# key only sends pings.
if [[ -z "${HEALTHCHECKS_API_KEY:-}" && -f .env ]]; then
    HEALTHCHECKS_API_KEY="$(sed -n 's/^HEALTHCHECKS_API_KEY=//p' .env | tail -1)"
    export HEALTHCHECKS_API_KEY
fi
# Flat, not a subdirectory: Grafana's alerting provisioner does not recurse, and it
# skips a directory with a warning rather than an error — so a nested layout looks like
# it worked and provisions nothing. The project- prefix keeps them grouped in `ls`.
out_dir="config/grafana/alerting"

# Pinned tag for the vendoring curl. A moving ref would let two projects vendor two
# different agent configs and call it the same template.
tag="$(git -C "$root" describe --tags --abbrev=0 2>/dev/null || echo main)"
repo_raw="https://raw.githubusercontent.com/CMLPlatform/monitoring/${tag}/templates"

# ---------------------------------------------------------------- 1. the keystone rule
rendered="${out_dir}/project-${project}-${env_name}.yaml"
sed -e "s/__PROJECT__/${project}/g" \
    -e "s/__ENV__/${env_name}/g" \
    -e "s/__UID__/proj-silent-${project}-${env_name}/g" \
    templates/alerting/project.yaml.tmpl > "$rendered"
echo "rendered  $rendered"

# ------------------------------------------------------------ 2. the coverage backstop
# Every project with a rendered rule file, derived from the directory rather than a list
# someone has to remember to update.
covered="$(find "$out_dir" -maxdepth 1 -name 'project-*.yaml' -exec basename {} .yaml \; \
           | sed -e 's/^project-//' -e 's/-[^-]*$//' | sort -u | paste -sd'|' -)"
: "${covered:=__none__}"
cat > "${out_dir}/coverage.yaml" <<COVERAGE
# GENERATED by bootstrap.sh — do not edit. Regenerated on every run.
#
# The trap this closes: ProjectTelemetrySilent only exists for projects bootstrap.sh was
# actually run for. A project that ships telemetry but skipped bootstrap is silently
# uncovered — the exact failure class the keystone closes, one level up. This fires on
# any series carrying a project label that has no rendered rule file.
#
# Covered right now: ${covered}

apiVersion: 1

groups:
  - orgId: 1
    name: _coverage
    folder: Stack alerts
    interval: 5m
    rules:
      - uid: projects-uncovered
        title: ProjectsUncovered
        condition: FIRING
        for: 15m
        noDataState: OK
        execErrState: Error
        isPaused: false
        data:
          - refId: QUERY
            datasourceUid: prometheus
            relativeTimeRange:
              from: 3600
              to: 0
            model:
              refId: QUERY
              instant: true
              editorMode: code
              expr: count by (project) ({project!~"${covered}", project!=""})
          - refId: FIRING
            datasourceUid: __expr__
            model:
              refId: FIRING
              type: threshold
              expression: QUERY
              conditions:
                - evaluator:
                    type: gt
                    params: [0]
        labels:
          severity: warning
        annotations:
          summary: "Project {{ \$labels.project }} is sending telemetry but has no alert rules"
          description: "Telemetry is arriving for a project bootstrap.sh was never run for, so nothing would notice if it went silent. Run ./bootstrap.sh {{ \$labels.project }} <env> on the monitoring host."
COVERAGE
echo "rendered  ${out_dir}/coverage.yaml  (covering: ${covered})"

# ------------------------------------------------------------------ 3. reload Grafana
if docker compose ps --status running --format '{{.Service}}' 2>/dev/null | grep -qx grafana; then
    # Provisioned files are re-read on SIGHUP; no restart, no dropped evaluations.
    # A restart, not SIGHUP: Grafana re-reads alert provisioning only at startup, and
    # a SIGHUP reports success while changing nothing.
    docker compose up -d --force-recreate grafana >/dev/null 2>&1 \
        && echo "reloaded  grafana (restarted)" \
        || echo "WARNING: could not restart grafana; run 'docker compose up -d --force-recreate grafana'" >&2
else
    echo "note      grafana is not running; the rules apply next time it starts"
fi

# ------------------------------------------------------- 4. healthchecks.io + printout
hc_note="create these by hand at https://healthchecks.io and note their ping URLs"
if [[ -n "${HEALTHCHECKS_API_KEY:-}" ]]; then
    hc_note="created via API"
    for job in backup watchdog restore-check; do
        curl -fsS -X POST https://healthchecks.io/api/v3/checks/ \
            -H "X-Api-Key: ${HEALTHCHECKS_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"${project}-${env_name}-${job}\",\"slug\":\"${project}-${env_name}-${job}\",\"unique\":[\"name\"],\"timeout\":93600,\"grace\":3600,\"channels\":\"*\"}" \
            | sed -n 's/.*"ping_url": *"\([^"]*\)".*/  PING_'"$(echo "$job" | tr 'a-z-' 'A-Z_')"'=\1/p'
    done
else
    echo "note      HEALTHCHECKS_API_KEY unset; ${hc_note}"
fi

cat <<SUMMARY

────────────────────────────────────────────────────────────────────────────
Paste this into the project host's root .env
────────────────────────────────────────────────────────────────────────────
PROJECT=${project}
ENVIRONMENT=${env_name}
OTEL_EXPORTER_OTLP_ENDPOINT=https://<otlp-hostname>
OTLP_AUTH_TOKEN=<the stack's shared ingest token>
TELEMETRY_EDGE_KEY=            # only if the project's egress crosses a WAF
GPU_METRICS=                   # 1 on hosts with an NVIDIA card

────────────────────────────────────────────────────────────────────────────
Vendor the templates on the project host (pinned at ${tag})
────────────────────────────────────────────────────────────────────────────
mkdir -p deploy/alloy scripts
curl -fsSL -o deploy/alloy/config.alloy   ${repo_raw}/alloy/config.alloy
curl -fsSL -o compose.telemetry.yml       ${repo_raw}/compose.telemetry.yml
curl -fsSL -o compose.telemetry.gpu.yml   ${repo_raw}/compose.telemetry.gpu.yml
curl -fsSL -o scripts/run_scheduled.sh    ${repo_raw}/run_scheduled.sh
chmod +x scripts/run_scheduled.sh

Then include the overlay and bring it up:
  docker compose -f compose.yaml -f compose.telemetry.yml up -d

The agent container needs 'cgroup: host' (the overlay sets it). Without it cAdvisor
reports the root cgroup only, and every container alert here matches nothing.

Verify from the monitoring host, within ~2 minutes:
  count({project="${project}",env="${env_name}"})            -> non-zero
  count(container_start_time_seconds{project="${project}",name!=""})  -> one per container
SUMMARY
